### PR TITLE
📝 Added eslint-plugin-jsdoc and fixed errors 

### LINKED ISSUE #132: Add `eslint-plugin-jsdoc` to standardize documentation
Plugin also works on Typescript/TSDoc. Should throw warnings about incomplete documentation, extended from `plugin:jsdoc/recommended` defaults.

Also requires fixing all the documentation that errors are thrown on

### PR DESCRIPTION
**Pull request by arimgibson**
Closes #132 

- [x] Added `eslint-plugin-jsdoc`
- [x] Configured eslint to use plugin
- [x] Changed plugin rules as needed
- [ ] Fixed warnings thrown by plugin

### CODE REVIEW

**Comment by arimgibson** [comment]
@dawsbot I got lost trying to document these last ones because they deal with contracts. Leaving these last ones for you; besides those, I think this is merge ready.

```
C:\coding\essential-eth\src\classes\Contract.ts
   10:1  warning  Missing JSDoc @param "txnData" description  jsdoc/require-param-description
   11:1  warning  Missing JSDoc @example description          jsdoc/require-example
   35:1  warning  Missing JSDoc @example description          jsdoc/require-example
  101:1  warning  Missing JSDoc @param "object" description   jsdoc/require-param-description
  102:1  warning  Missing JSDoc @param "name" description     jsdoc/require-param-description
  103:1  warning  Missing JSDoc @param "value" description    jsdoc/require-param-description
  104:1  warning  Missing JSDoc @example description          jsdoc/require-example

C:\coding\essential-eth\src\classes\utils\encode-decode-transaction.ts
   30:1  warning  Missing JSDoc @returns declaration                  jsdoc/require-returns
   32:1  warning  Missing JSDoc @param "jsonABIArgument" description  jsdoc/require-param-description
   33:1  warning  Missing JSDoc @param "args" description             jsdoc/require-param-description
   34:1  warning  Missing JSDoc @example description                  jsdoc/require-example
  113:1  warning  Missing JSDoc @returns declaration                  jsdoc/require-returns
  115:1  warning  Missing JSDoc @param "jsonABIArgument" description  jsdoc/require-param-description
  116:1  warning  Missing JSDoc @param "nodeResponse" description     jsdoc/require-param-description
  117:1  warning  Missing JSDoc @example description                  jsdoc/require-example
```

File: src/classes/utils/encode-decode-transaction.ts [hunk 1]
```diff
@@ -15,6 +27,12 @@ function expandType(type: ContractTypes) {
   }
   return type;
 }
+/**
+ *
+ * @param jsonABIArgument
+ * @param args
+ * @example
```
Comment (dawsbot) [inline src/classes/utils/encode-decode-transaction.ts:34]: Is this empty `@example` statement intentional? Seems like it was thrown in to skip a warning from the eslint rule, but we do want examples for everything

File: src/classes/utils/encode-decode-transaction.ts [hunk 2]
```diff
@@ -15,6 +27,12 @@ function expandType(type: ContractTypes) {
   }
   return type;
 }
+/**
+ *
+ * @param jsonABIArgument
```
Comment (dawsbot) [inline src/classes/utils/encode-decode-transaction.ts:32]: We don't need `@param` lines like this because TS automatically documents these by the function definition

**Review by dawsbot — CHANGES_REQUESTED** [review]

File: src/classes/utils/encode-decode-transaction.ts (hunk 1 above)
Comment (arimgibson) [reply src/classes/utils/encode-decode-transaction.ts:34]: That'll still throw an error actually (`jsdoc/require-example`). The empty is added through `eslint --fix` using the JSDoc plugin

File: src/classes/utils/encode-decode-transaction.ts (hunk 2 above)
Comment (arimgibson) [reply src/classes/utils/encode-decode-transaction.ts:32]: https://github.com/Earnifi/essential-eth/pull/133#discussion_r885057998

Also added through `eslint --fix` but still throws warning until the description is added (`jsdoc/require-description`)
